version: "3"

services:
  todo-db:
    container_name: todo-db
    image: postgres:14-alpine
    env_file: [.env]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - db-rustodo:/var/lib/postgresql/data:rw

volumes:
  db-rustodo:
